In [1]:
# Importing necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Loading the dataset
Fraud_train = pd.read_csv("fraudTrain.csv")
Fraud_test = pd.read_csv("fraudTest.csv")

In [4]:
# Displaying the rows of the train dataset
Fraud_train.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095   
1           1   2019-01-01 00:00:44      630423337322   
2           2   2019-01-01 00:00:51    38859492057661   
3           3   2019-01-01 00:01:16  3534093764340240   
4           4   2019-01-01 00:03:06   375534208663984   

                             merchant       category     amt      first  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer   
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie   
2                fraud_Lind-Buckridge  entertainment  220.11     Edward   
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy   
4                 fraud_Keeling-Crist       misc_pos   41.96      Tyler   

      last gender                        street  ...      lat      long  \
0    Banks      F                561 Perry Cove  ...  36.0788  -81.1781   
1     Gill      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105   
2  Sanchez      M      594 White Dale Suite 530  ...  42.1808 -112.2620   
3    White      M   9443 Cynthia Court Apt. 038  ...  46.2306 -112.1138   
4   Garcia      M              408 Bradley Rest  ...  38.4207  -79.4629   

   city_pop                                job         dob  \
0      3495          Psychologist, counselling  1988-03-09   
1       149  Special educational needs teacher  1978-06-21   
2      4154        Nature conservation officer  1962-01-19   
3      1939                    Patent attorney  1967-01-12   
4        99     Dance movement psychotherapist  1986-03-28   

                          trans_num   unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1325376018  36.011293  -82.048315   
1  1f76529f8574734946361c461b024d99  1325376044  49.159047 -118.186462   
2  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704 -112.154481   
3  6b849c168bdad6f867558c3793159a81  1325376076  47.034331 -112.561071   
4  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999  -78.632459   

   is_fraud  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 23 columns]

In [5]:
# Displaying the rows of the test dataset
Fraud_test.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2020-06-21 12:14:25  2291163933867244   
1           1   2020-06-21 12:14:33  3573030041201292   
2           2   2020-06-21 12:14:53  3598215285024754   
3           3   2020-06-21 12:15:15  3591919803438423   
4           4   2020-06-21 12:15:17  3526826139003047   

                               merchant        category    amt   first  \
0                 fraud_Kirlin and Sons   personal_care   2.86    Jeff   
1                  fraud_Sporer-Keebler   personal_care  29.84  Joanne   
2  fraud_Swaniawski, Nitzsche and Welch  health_fitness  41.28  Ashley   
3                     fraud_Haley Group        misc_pos  60.05   Brian   
4                 fraud_Johnston-Casper          travel   3.19  Nathan   

       last gender                       street  ...      lat      long  \
0   Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1  Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2     Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3  Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4    Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   

   city_pop                     job         dob  \
0    333497     Mechanical engineer  1968-03-19   
1       302  Sales professional, IT  1990-01-17   
2     34496       Librarian, public  1970-10-21   
3     54767            Set designer  1987-07-25   
4      1126      Furniture designer  1955-07-06   

                          trans_num   unix_time  merch_lat  merch_long  \
0  2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714   
1  324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431   
2  c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111   
3  2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061   
4  57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734   

   is_fraud  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 23 columns]

In [6]:
# Checking the shape (number of rows and columns) of the train and test dataset
print(Fraud_train.shape)
print(Fraud_test.shape)

(1296675, 23)
(555719, 23)


In [7]:
# combining train and test datasets
Fraud_data = pd.concat([Fraud_train,Fraud_test],ignore_index =True)

In [8]:
# Displaying the first 5 rows of the dataset
Fraud_data.head(5)

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095   
1           1   2019-01-01 00:00:44      630423337322   
2           2   2019-01-01 00:00:51    38859492057661   
3           3   2019-01-01 00:01:16  3534093764340240   
4           4   2019-01-01 00:03:06   375534208663984   

                             merchant       category     amt      first  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer   
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie   
2                fraud_Lind-Buckridge  entertainment  220.11     Edward   
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy   
4                 fraud_Keeling-Crist       misc_pos   41.96      Tyler   

      last gender                        street  ...      lat      long  \
0    Banks      F                561 Perry Cove  ...  36.0788  -81.1781   
1     Gill      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105   
2  Sanchez      M      594 White Dale Suite 530  ...  42.1808 -112.2620   
3    White      M   9443 Cynthia Court Apt. 038  ...  46.2306 -112.1138   
4   Garcia      M              408 Bradley Rest  ...  38.4207  -79.4629   

   city_pop                                job         dob  \
0      3495          Psychologist, counselling  1988-03-09   
1       149  Special educational needs teacher  1978-06-21   
2      4154        Nature conservation officer  1962-01-19   
3      1939                    Patent attorney  1967-01-12   
4        99     Dance movement psychotherapist  1986-03-28   

                          trans_num   unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1325376018  36.011293  -82.048315   
1  1f76529f8574734946361c461b024d99  1325376044  49.159047 -118.186462   
2  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704 -112.154481   
3  6b849c168bdad6f867558c3793159a81  1325376076  47.034331 -112.561071   
4  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999  -78.632459   

   is_fraud  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 23 columns]

In [9]:
# Checking the shape (number of rows and columns) of the dataset
print(Fraud_data.shape)

(1852394, 23)


In [10]:
# Displaying summary statistics of the dataset
Fraud_data.describe()

Unnamed: 0        cc_num           amt           zip           lat  \
count  1.852394e+06  1.852394e+06  1.852394e+06  1.852394e+06  1.852394e+06   
mean   5.371934e+05  4.173860e+17  7.006357e+01  4.881326e+04  3.853931e+01   
std    3.669110e+05  1.309115e+18  1.592540e+02  2.688185e+04  5.071470e+00   
min    0.000000e+00  6.041621e+10  1.000000e+00  1.257000e+03  2.002710e+01   
25%    2.315490e+05  1.800429e+14  9.640000e+00  2.623700e+04  3.466890e+01   
50%    4.630980e+05  3.521417e+15  4.745000e+01  4.817400e+04  3.935430e+01   
75%    8.335758e+05  4.642255e+15  8.310000e+01  7.204200e+04  4.194040e+01   
max    1.296674e+06  4.992346e+18  2.894890e+04  9.992100e+04  6.669330e+01   

               long      city_pop     unix_time     merch_lat    merch_long  \
count  1.852394e+06  1.852394e+06  1.852394e+06  1.852394e+06  1.852394e+06   
mean  -9.022783e+01  8.864367e+04  1.358674e+09  3.853898e+01 -9.022794e+01   
std    1.374789e+01  3.014876e+05  1.819508e+07  5.105604e+00  1.375969e+01   
min   -1.656723e+02  2.300000e+01  1.325376e+09  1.902742e+01 -1.666716e+02   
25%   -9.679800e+01  7.410000e+02  1.343017e+09  3.474012e+01 -9.689944e+01   
50%   -8.747690e+01  2.443000e+03  1.357089e+09  3.936890e+01 -8.744069e+01   
75%   -8.015800e+01  2.032800e+04  1.374581e+09  4.195626e+01 -8.024511e+01   
max   -6.795030e+01  2.906700e+06  1.388534e+09  6.751027e+01 -6.695090e+01   

           is_fraud  
count  1.852394e+06  
mean   5.210015e-03  
std    7.199217e-02  
min    0.000000e+00  
25%    0.000000e+00  
50%    0.000000e+00  
75%    0.000000e+00  
max    1.000000e+00

In [11]:
# Checking for missing values in the dataset
Fraud_data.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [12]:
# Dropping missing values in the dataset
Fraud_data.dropna(axis=0)

Unnamed: 0 trans_date_trans_time            cc_num  \
0                 0   2019-01-01 00:00:18  2703186189652095   
1                 1   2019-01-01 00:00:44      630423337322   
2                 2   2019-01-01 00:00:51    38859492057661   
3                 3   2019-01-01 00:01:16  3534093764340240   
4                 4   2019-01-01 00:03:06   375534208663984   
...             ...                   ...               ...   
1852389      555714   2020-12-31 23:59:07    30560609640617   
1852390      555715   2020-12-31 23:59:09  3556613125071656   
1852391      555716   2020-12-31 23:59:15  6011724471098086   
1852392      555717   2020-12-31 23:59:24     4079773899158   
1852393      555718   2020-12-31 23:59:34  4170689372027579   

                                   merchant        category     amt  \
0                fraud_Rippin, Kub and Mann        misc_net    4.97   
1           fraud_Heller, Gutmann and Zieme     grocery_pos  107.23   
2                      fraud_Lind-Buckridge   entertainment  220.11   
3        fraud_Kutch, Hermiston and Farrell   gas_transport   45.00   
4                       fraud_Keeling-Crist        misc_pos   41.96   
...                                     ...             ...     ...   
1852389               fraud_Reilly and Sons  health_fitness   43.77   
1852390                fraud_Hoppe-Parisian       kids_pets  111.84   
1852391                     fraud_Rau-Robel       kids_pets   86.88   
1852392               fraud_Breitenberg LLC          travel    7.99   
1852393                   fraud_Dare-Marvin   entertainment   38.13   

             first     last gender                        street  ...  \
0         Jennifer    Banks      F                561 Perry Cove  ...   
1        Stephanie     Gill      F  43039 Riley Greens Suite 393  ...   
2           Edward  Sanchez      M      594 White Dale Suite 530  ...   
3           Jeremy    White      M   9443 Cynthia Court Apt. 038  ...   
4            Tyler   Garcia      M              408 Bradley Rest  ...   
...            ...      ...    ...                           ...  ...   
1852389    Michael    Olson      M           558 Michael Estates  ...   
1852390       Jose  Vasquez      M           572 Davis Mountains  ...   
1852391        Ann   Lawson      F    144 Evans Islands Apt. 683  ...   
1852392       Eric  Preston      M    7020 Doyle Stream Apt. 951  ...   
1852393     Samuel     Frey      M      830 Myers Plaza Apt. 384  ...   

             lat      long  city_pop                                job  \
0        36.0788  -81.1781      3495          Psychologist, counselling   
1        48.8878 -118.2105       149  Special educational needs teacher   
2        42.1808 -112.2620      4154        Nature conservation officer   
3        46.2306 -112.1138      1939                    Patent attorney   
4        38.4207  -79.4629        99     Dance movement psychotherapist   
...          ...       ...       ...                                ...   
1852389  40.4931  -91.8912       519                       Town planner   
1852390  29.0393  -95.4401     28739                     Futures trader   
1852391  46.1966 -118.9017      3684                           Musician   
1852392  44.6255 -116.4493       129                       Cartographer   
1852393  35.6665  -97.4798    116001                        Media buyer   

                dob                         trans_num   unix_time  merch_lat  \
0        1988-03-09  0b242abb623afc578575680df30655b9  1325376018  36.011293   
1        1978-06-21  1f76529f8574734946361c461b024d99  1325376044  49.159047   
2        1962-01-19  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704   
3        1967-01-12  6b849c168bdad6f867558c3793159a81  1325376076  47.034331   
4        1986-03-28  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999   
...             ...                               ...         ...        ...   
1852389  1966-02-13  9b1f753c79894c9f4b71f04581835ada  138853

In [13]:
# dropping missing Values in the columns of the dataset
columns_with_nulls = ["cc_num", "merchant", "category", "amt","first","last","gender","street","city","state","zip","lat","long","city_pop","job","dob","trans_num","unix_time","merch_lat","merch_long","is_fraud"]
Fraud_data = Fraud_data.dropna(subset=columns_with_nulls)

In [14]:
# Checking for missing values in the dataset
Fraud_data.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [15]:
# Replacing duplicates with sum of that column
Fraud_data.duplicated().sum()

0

In [16]:
# Displaying the columns of the dataset
Fraud_data.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [17]:
Fraud_data1 = Fraud_data.drop(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
                               'first', 'last', 'gender', 'street', 'city', 'state', 'city_pop','dob',
                               'trans_num','unix_time','merch_lat', 'merch_long'],axis=1)


In [18]:
# Displaying the first 5 rows of the dataset
Fraud_data1.head(5)

amt    zip      lat      long                                job  \
0    4.97  28654  36.0788  -81.1781          Psychologist, counselling   
1  107.23  99160  48.8878 -118.2105  Special educational needs teacher   
2  220.11  83252  42.1808 -112.2620        Nature conservation officer   
3   45.00  59632  46.2306 -112.1138                    Patent attorney   
4   41.96  24433  38.4207  -79.4629     Dance movement psychotherapist   

   is_fraud  
0         0  
1         0  
2         0  
3         0  
4         0

In [19]:
Fraud_data1.job.value_counts()
Fraud_data1.job=pd.Categorical(Fraud_data1.job).codes
Fraud_data1

amt    zip      lat      long  job  is_fraud
0          4.97  28654  36.0788  -81.1781  372         0
1        107.23  99160  48.8878 -118.2105  431         0
2        220.11  83252  42.1808 -112.2620  308         0
3         45.00  59632  46.2306 -112.1138  330         0
4         41.96  24433  38.4207  -79.4629  116         0
...         ...    ...      ...       ...  ...       ...
1852389   43.77  63453  40.4931  -91.8912  477         0
1852390  111.84  77566  29.0393  -95.4401  207         0
1852391   86.88  99323  46.1966 -118.9017  307         0
1852392    7.99  83643  44.6255 -116.4493   63         0
1852393   38.13  73034  35.6665  -97.4798  289         0

[1852394 rows x 6 columns]

In [20]:
# Defining the Features/Independent Variables (X) and Target variable/Dependent Variable (y) 
X_data = Fraud_data1.drop('is_fraud', axis=1)
y_target = Fraud_data1['is_fraud']

In [21]:
# Importing necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [22]:
# Splitting the dataset 
X_train,X,Y_train,Y = train_test_split(X_data,y_target,test_size = 0.3,random_state=2)

In [23]:
X_Val,X_test,Y_Val,Y_test = train_test_split(X,Y,test_size = 0.5,random_state=2)

In [24]:
# Model 1: Logistic Regression
logistic_model = LogisticRegression()
logistic_model=logistic_model.fit(X_train, Y_train)
logistic_predictions = logistic_model.predict(X_test)

In [25]:
# Model 2: Decision Tree
tree_model = DecisionTreeClassifier(max_depth = 5)
tree_model=tree_model.fit(X_train, Y_train)
tree_predictions = tree_model.predict(X_test)

In [26]:
# Model 3: Random Forest
forest_model = RandomForestClassifier(n_estimators=50,max_depth = 5,random_state = 2)
forest_model=forest_model.fit(X_train, Y_train)
forest_predictions = forest_model.predict(X_test)

In [27]:

name = {
    "LR": logistic_model,
    "DTC":tree_model,
    "RFC":forest_model ,   
}

In [28]:
#Evaluation
def evaluate_model(name, predictions):
    print(f"------- {name} -------")
    print("Accuracy:", accuracy_score(Y_test, predictions))
    print("Confusion Matrix:\n", confusion_matrix(Y_test, predictions))
    print("Classification Report:\n", classification_report(Y_test, predictions))


In [29]:
# Displaying predictions of logistic regression model
print(logistic_predictions)

[0 0 0 ... 0 0 0]


In [30]:
# Displaying predictions of Decision Tree model
print(tree_predictions)

[0 0 0 ... 0 0 0]


In [31]:
# Displaying predictions of Random Forest Model
print(forest_predictions)

[0 0 0 ... 0 0 0]


In [32]:
# Evaluating logistic Regression model
evaluate_model("Logistic Regression", logistic_predictions)

------- Logistic Regression -------
Accuracy: 0.9941985172388973
Confusion Matrix:
 [[276248    123]
 [  1489      0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00    276371
           1       0.00      0.00      0.00      1489

    accuracy                           0.99    277860
   macro avg       0.50      0.50      0.50    277860
weighted avg       0.99      0.99      0.99    277860



In [33]:
# Evaluating Decision Tree model
evaluate_model("Decision Tree", tree_predictions)

------- Decision Tree -------
Accuracy: 0.9949650903332613
Confusion Matrix:
 [[276101    270]
 [  1129    360]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    276371
           1       0.57      0.24      0.34      1489

    accuracy                           0.99    277860
   macro avg       0.78      0.62      0.67    277860
weighted avg       0.99      0.99      0.99    277860



In [34]:
# Evaluating Random Forest model
evaluate_model("Random Forest", forest_predictions)

------- Random Forest -------
Accuracy: 0.9946627798171741
Confusion Matrix:
 [[276369      2]
 [  1481      8]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00    276371
           1       0.80      0.01      0.01      1489

    accuracy                           0.99    277860
   macro avg       0.90      0.50      0.50    277860
weighted avg       0.99      0.99      0.99    277860

